In [1]:
import pandas as pd
import numpy as np

In [2]:
daily_basic = pd.read_csv('daily_basic.csv')
fina_indicator = pd.read_csv('fina_indicator.csv')
pro_bar = pd.read_csv('pro_bar.csv')

In [3]:
daily_basic.shape

(873815, 14)

In [4]:
daily_basic.head()

,ts_code,trade_date,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_mv,circ_mv
0,000001.SZ,20190102,0.3141,0.7088,0.99,6.8048,6.4428,0.7330,1.4917,1.4012,1.48,1.48,1.577961e+07,1.577946e+07
1,000001.SZ,20190103,0.2420,0.5460,0.76,6.8714,6.5059,0.7402,1.5063,1.4149,1.47,1.47,1.593414e+07,1.593399e+07
2,000001.SZ,20190104,0.8626,1.9463,2.87,7.2194,6.7456,0.7607,1.5825,1.4343,1.39,1.39,1.674115e+07,1.674099e+07
3,000001.SZ,20190107,0.5042,1.1375,1.19,7.2120,6.7386,0.7599,1.5809,1.4329,1.40,1.40,1.672398e+07,1.672382e+07
4,000001.SZ,20190108,0.2344,0.5287,0.52,7.1528,6.6833,0.7536,1.5679,1.4211,1.41,1.41,1.658662e+07,1.658646e+07

In [5]:
fina_indicator.shape

(11190, 6)

In [6]:
fina_indicator.head()

     ts_code    ann_date  end_date   profit_dedt      roe     roa
0  000001.SZ  20191022.0  20190930  2.352700e+10   8.9454     NaN
1  000001.SZ  20190808.0  20190630  1.531600e+10   6.2028     NaN
2  000001.SZ  20190424.0  20190331  7.422000e+09   3.0331     NaN
3  000002.SZ  20191025.0  20190930  1.817556e+10  11.2933  2.9457
4  000002.SZ  20190821.0  20190630  1.174968e+10   7.4763  2.0049

In [7]:
pro_bar.shape

(875563, 11)

In [8]:
pro_bar.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000001.SZ,20191227,16.53,16.93,16.43,16.63,16.47,0.16,0.9715,1042574.72,1741473.179
1,000001.SZ,20191226,16.34,16.48,16.32,16.47,16.30,0.17,1.0429,372033.86,610381.757
2,000001.SZ,20191225,16.45,16.56,16.24,16.30,16.40,-0.10,-0.6098,414917.98,679664.596
3,000001.SZ,20191224,16.23,16.50,16.23,16.40,16.24,0.16,0.9852,459128.42,752351.618
4,000001.SZ,20191223,16.68,16.68,16.17,16.24,16.59,-0.35,-2.1097,715792.72,1173372.080

In [9]:
# 将行情数据与财务数据结合
daily_basic_pro_bar = daily_basic.merge(pro_bar, left_on=['ts_code', 'trade_date'], right_on=['ts_code', 'trade_date'])
# 新股在merge中会丢失一部分财务信息
factor_model = daily_basic_pro_bar.merge(fina_indicator, left_on=['ts_code', 'trade_date'], right_on=['ts_code', 'ann_date'], how='left')
daily_basic_pro_bar.to_csv('daily_basic_w_pro_bar.csv', index=0)
factor_model.to_csv('factor_model.csv', index=0)

In [10]:
# 财务指标使用前值填充空缺
# 同一标的才能fillna！
col = fina_indicator.columns[3:]
factor_model[col] = factor_model.groupby('ts_code')[col].transform(lambda x: x.fillna(method='ffill', axis=0))
factor_model.to_csv('factor_model_fillna.csv', index=0)

In [11]:
factor_model

,ts_code,trade_date,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,...,pre_close,change,pct_chg,vol,amount,ann_date,end_date,profit_dedt,roe,roa
0,000001.SZ,20190102,0.3141,0.7088,0.99,6.8048,6.4428,0.7330,1.4917,1.4012,...,9.2822,-0.1880,-2.0254,539386.32,498695.109,NaN,NaN,NaN,NaN,NaN
1,000001.SZ,20190103,0.2420,0.5460,0.76,6.8714,6.5059,0.7402,1.5063,1.4149,...,9.0942,0.0891,0.9797,415537.95,384457.707,NaN,NaN,NaN,NaN,NaN
2,000001.SZ,20190104,0.8626,1.9463,2.87,7.2194,6.7456,0.7607,1.5825,1.4343,...,9.1833,0.4651,5.0646,1481159.06,1422149.888,NaN,NaN,NaN,NaN,NaN
3,000001.SZ,20190107,0.5042,1.1375,1.19,7.2120,6.7386,0.7599,1.5809,1.4329,...,9.6484,-0.0099,-0.1026,865687.66,841166.430,NaN,NaN,NaN,NaN,NaN
4,000001.SZ,20190108,0.2344,0.5287,0.52,7.1528,6.6833,0.7536,1.5679,1.4211,...,9.6385,-0.0792,-0.8217,402388.11,389247.795,NaN,NaN,NaN,NaN,NaN
5,000001.SZ,20190109,0.7184,1.6208,1.67,7.3601,6.8770,0.7755,1.6134,1.4623,...,9.5593,0.2771,2.8987,1233486.36,1229465.116,NaN,NaN,NaN,NaN,NaN
6,000001.SZ,20190110,0.6242,1.4084,1.22,7.4786,6.9877,0.7880,1.6394,1.4858,...,9.8364,0.1583,1.6093,1071817.66,1079711.035,NaN,NaN,NaN,NaN,NaN
7,000001.SZ,20190111,0.4056,0.9150,0.69,7.5526,7.0569,0.7958,1.6556,1.5006,...,9.9947,0.0990,0.9905,696364.55,708001.802,NaN,NaN,NaN,NaN,NaN
8,000001.SZ,20190114,0.2915,0.6576,0.59,7.4860,6.9946,0.7887,1.6410,1.4873,...,10.0937,-0.0891,-0.8827,500443.59,507862.882,NaN,NaN,NaN,NaN,NaN
9,000001.SZ,20190115,0.3158,0.7124,0.69,7.5823,7.0846,0.7989,1.6621,1.5064,...,10.0046,0.1287,1.2864,542160.55,553027.309,NaN,NaN,NaN,NaN,NaN
10,000001.SZ,20190116,0.5694,1.2847,1.21,7.7600,7.2506,0.8176,1.7010,1.5417,...,10.1333,0.2375,2.3438,977699.37,1017495.116,NaN,NaN,NaN,NaN,NaN
11,000001.SZ,20190117,0.5142,1.1600,1.17,7.5897,7.0915,0.7997,1.6637,1.5079,...,10.3708,-0.2276,-2.1946,882811.92,910212.066,NaN,NaN,NaN,NaN,NaN
12,000001.SZ,20190118,0.4303,0.9708,1.03,7.7229,7.2160,0.8137,1.6929,1.5344,...,10.1432,0.1781,1.7559,738793.26,769973.637,NaN,NaN,NaN,NaN,NaN
13,000001.SZ,20190121,0.3840,0.8664,0.91,7.6563,7.1538,0.8067,1.6783,1.5211,...,10.3213,-0.0891,-0.8633,659355.76,684465.646,NaN,NaN,NaN,NaN,NaN
14,000001.SZ,20190122,0.2472,0.5577,0.56,7.6119,7.1123,0.8020,1.6686,1.5123,...,10.2322,-0.0594,-0.5805,424413.57,438991.450,NaN,NaN,NaN,NaN,NaN
15,000001.SZ,20190123,0.3133,0.7068,0.73,7.6637,7.1607,0.8075,1.6799,1.5226,...,10.1728,0.0693,0.6812,537876.63,559384.396,NaN,NaN,NaN,NaN,NaN
16,000001.SZ,20190124,0.3956,0.8925,1.05,7.7896,7.2783,0.8207,1.7075,1.5476,...,10.2421,0.1682,1.6422,679240.88,711495.718,NaN,NaN,NaN,NaN,NaN
17,000001.SZ,20190125,1.2279,2.7704,3.47,8.1450,7.6104,0.8582,1.7854,1.6182,...,10.4103,0.4750,4.5628,2108361.85,2299718.224,NaN,NaN,NaN,NaN,NaN
18,000001.SZ,20190128,0.6033,1.3612,1.17,8.1006,7.5689,0.8535,1.7757,1.6094,...,10.8853,-0.0593,-0.5448,1035909.80,1141853.833,NaN,NaN,NaN,NaN,NaN
19,000001.SZ,20190129,0.4814,1.0862,0.86,8.1450,7.6104,0.8582,1.7854,1.6182,...,10.8260,0.0593,0.5478,826631.10,904847.854,NaN,NaN,NaN,NaN,NaN
20,000001.SZ,20190130,0.4147,0.9356,0.69,8.1080,7.5758,0.8543,1.7773,1.6109,...,10.8853,-0.0494,-0.4538,712001.01,785204.571,NaN,NaN,NaN,NaN,NaN
21,000001.SZ,20190131,0.4843,1.0928,0.78,8.2191,7.6796,0.8660,1.8017,1.6330,...,10.8359,0.1484,1.3695,831622.75,922602.874,NaN,NaN,NaN,NaN,NaN
22,000001.SZ,20190201,0.5907,1.3328,0.92,8.2931,7.7488,0.8738,1.8179,1.6477,...,10.9843,0.0989,0.9004,1014270.07,1127216.186,NaN,NaN,NaN,NaN,NaN
23,000001.SZ,20190211,0.4671,1.0538,0.91,8.3005,7.7557,0.8746,1.8195,1.6491,...,11.0832,0.0099,0.0893,801936.63,889951.528,NaN,NaN,NaN,NaN,NaN
24,000001.SZ,20190212,0.5591,1.2614,1.15,8.2857,7.7418,0.8730,1.8163,1.6462,...,11.0931,-0.0197,-0.1776,959936.90,1071873.084,NaN,NaN,NaN,NaN,NaN
25,000001.SZ,20190213,0.6624,1.4945,1.32,8.4264,7.8733,0.8878,1.8471,1.6741,...,11.0734,0.1880,1.6978,1137365.74,1280182.096,NaN,NaN,NaN,NaN,NaN
26,000001.SZ,20190214,0.5062,1.1421,0.92,8.3301,7.7833,0.8777,1.8260,1.6550,...,11.2614,-0.1287,-1.1428,869185.19,977818.097,NaN,NaN,NaN,NaN,NaN
27,000001.SZ,20190215,0.6407,1.4456,1.15,8.1080,7.5758,0.8543,1.7773,1.6109,...,11.1327,-0.2968,-2.6660,1100127.46,1213914.428,NaN,NaN,NaN,NaN,NaN
28,000001.SZ,20190219,0.7402,1.6700,1.19,8.3449,7.7972,0.8792,1.8293,1.6580,...,11.2416,-0.0891,-0.7926,1270882.04,1445281.382,NaN,NaN,NaN,NaN,NaN
29,000001.SZ,20190220,0.4849,1.0941,0.74,8.4486,7.8940,0.8902,1.8520,1.6786,...,11.1525,0.1386,1.2428,832629.87,949430.819,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871978,688389.SH,20191211,14.4202,14.4202,1.20,83.5097,66.1816,6.6748,20.9514,16.9611,...,16.7200,-0.6700,-4.0072,50112.72,81536.217,NaN,NaN,NaN,NaN,NaN
871979,688389.SH,20191212,9.0680,9.0680,0.69,82.4690,65.3569,6.5916,20.6904,16.7497,...,16.0500,-0.2000,-1.2461,31513.05,50692.109,NaN,NaN,NaN,NaN,NaN
871980,688389.SH,20191213,7.9810,7.9810,0.58,81.9487,64.9446,6.5500,20.5598,16.6440,...,15.8500,-0.1000,-0.6309,27735.42,43748.276,NaN,NaN,NaN,NaN,NaN
871981,688389.SH,20191216,7.1330,7.1330,0.53,83.0934,65.8517,6.6415,20.8470,16.8765,...,15.7500,0.2200,1.3968,24788.52,39392.584,NaN,NaN,NaN,NaN,NaN
871982,688389.SH,20191217,8.8186,8.8186,0.69,84.0820,66.6352,6.7205,21.0950,17.0773,...,15.9700,0.1900,1.1897,30646.25,49342.113,NaN,NaN,NaN,NaN,NaN
871983,688389.SH,20191218,16.4957,16.4957,1.74,87.4640,69.3155,6.9909,21.9435,17.7642,...,16.1600,0.6500,4.0223,57325.42,95053.577,NaN,NaN,NaN,NaN,NaN
871984,688389.SH,20191219,10.1578,10.1578,1.03,86.3193,68.4083,6.8994,21.6564,17.5317,...,16.8100,-0.2200,-1.3087,35300.14,58877.947,NaN,NaN,NaN,NaN,NaN
871985,688389.SH,20191220,11.6351,11.6351,1.15,86.6836,68.6969,6.9285,21.7477,17.6057,...,16.5900,0.0700,0.4219,40434.22,67702.107,NaN,NaN,NaN,NaN,NaN
871986,688389.SH,20191223,8.8294,8.8294,0.81,82.9373,65.7280,6.6291,20.8079,16.8448,...,16.6600,-0.7200,-4.3217,30683.69,49846.729,NaN,NaN,NaN,NaN,NaN
871987,688389.SH,20191224,4.6616,4.6616,0.42,84.2901,66.8001,6.7372,21.1473,17.1196,...,15.9400,0.2600,1.6311,16200.03,26085.437,NaN,NaN,NaN,NaN,NaN
871988,688389.SH,20191225,9.8420,9.8420,0.95,85.6429,67.8722,6.8453,21.4867,17.3943,...,16.2000,0.2600,1.6049,34202.73,56678.387,NaN,NaN,NaN,NaN,NaN
871989,688389.SH,20191226,10.0027,10.0027,1.11,87.8803,69.6453,7.0241,22.0480,17.8487,...,16.4600,0.4300,2.6124,34761.29,58157.688,NaN,NaN,NaN,NaN,NaN
871990,688389.SH,20191227,8.7140,8.7140,0.97,85.3307,67.6248,6.8204,21.4083,17.3309,...,16.8900,-0.4900,-2.9011,30282.86,50495.260,NaN,NaN,NaN,NaN,NaN
871991,688399.SH,20191205,74.0740,74.0740,NaN,50.4048,43.3223,3.2601,13.9448,12.2412,...,46.7800,8.1000,17.3151,98803.38,540241.027,NaN,NaN,NaN,NaN,NaN
871992,688399.SH,20191206,47.3652,47.3652,NaN,46.8412,40.2594,3.0296,12.9589,11.3758,...,54.8800,-3.8800,-7.0700,63177.87,332493.192,NaN,NaN,NaN,NaN,NaN
871993,688399.SH,20191209,33.5540,33.5540,NaN,46.4095,39.8884,3.0017,12.8395,11.2710,...,51.0000,-0.4700,-0.9216,44755.85,222462.086,NaN,NaN,NaN,NaN,NaN
871994,688399.SH,20191210,44.1293,44.1293,NaN,49.2843,42.3592,3.1876,13.6348,11.9691,...,50.5300,3.1300,6.1943,58861.73,314437.449,NaN,NaN,NaN,NaN,NaN
871995,688399.SH,20191211,30.3628,30.3628,NaN,49.5874,42.6197,3.2072,13.7186,12.0427,...,53.6600,0.3300,0.6150,40499.39,220729.387,NaN,NaN,NaN,NaN,NaN
871996,688399.SH,20191212,32.6674,32.6674,0.71,51.3416,44.1274,3.3207,14.2040,12.4688,...,53.9900,1.9100,3.5377,43573.35,245154.581,NaN,NaN,NaN,NaN,NaN
871997,688399.SH,20191213,18.6375,18.6375,0.50,51.1855,43.9932,3.3106,14.1608,12.4308,...,55.9000,-0.1700,-0.3041,24859.62,137076.043,NaN,NaN,NaN,NaN,NaN
871998,688399.SH,20191216,18.8731,18.8731,0.59,51.7641,44.4906,3.3480,14.3208,12.5714,...,55.7300,0.6300,1.1305,25173.78,140833.617,NaN,NaN,NaN,NaN,NaN
871999,688399.SH,20191217,19.4704,19.4704,0.67,51.5253,44.2853,3.3326,14.2548,12.5134,...,56.3600,-0.2600,-0.4613,25970.55,145270.488,NaN,NaN,NaN,NaN,NaN
872000,688399.SH,20191218,35.4419,35.4419,1.48,57.5871,49.4954,3.7246,15.9318,13.9855,...,56.1000,6.6000,11.7647,47274.08,279011.500,NaN,NaN,NaN,NaN,NaN
872001,688399.SH,20191219,24.7186,24.7186,0.99,53.8858,46.3141,3.4852,14.9078,13.0866,...,62.7000,-4.0300,-6.4274,32970.83,196242.459,NaN,NaN,NaN,NaN,NaN
872002,688399.SH,20191220,14.7622,14.7622,0.63,53.8858,46.3141,3.4852,14.9078,13.0866,...,58.6700,0.0000,0.0000,19690.51,116765.902,NaN,NaN,NaN,NaN,NaN
872003,688399.SH,20191223,14.4032,14.4032,0.64,53.8031,46.2430,3.4799,14.8849,13.0665,...,58.6700,-0.0900,-0.1534,19211.64,112063.843,NaN,NaN,NaN,NaN,NaN
872004,688399.SH,20191224,10.5304,10.5304,0.48,53.9776,46.3930,3.4912,14.9332,13.1089,...,58.5800,0.1900,0.3243,14045.99,82499.017,NaN,NaN,NaN,NaN,NaN
872005,688399.SH,20191225,10.9309,10.9309,0.55,54.0603,46.4641,3.4965,14.9561,13.1290,...,58.7700,0.0900,0.1531,14580.11,85929.383,NaN,NaN,NaN,NaN,NaN
872006,688399.SH,20191226,12.7043,12.7043,0.84,54.5562,46.8903,3.5286,15.0933,13.2494,...,58.8600,0.5400,0.9174,16945.64,100957.027,NaN,NaN,NaN,NaN,NaN
872007,688399.SH,20191227,18.2465,18.2465,1.44,52.3336,44.9800,3.3848,14.4784,12.7097,...,59.4000,-2.4200,-4.0741,24338.08,142290.976,NaN,NaN,NaN,NaN,NaN